name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
        
      - name: Rodar lint
        run: pnpm lint

      - name: Build all packages
        run: pnpm run build

      - name: Start backend in background
        run: pnpm --filter @ts/backend start &

      - name: Wait for backend to be ready
        run: |
          for i in {1..15}; do
            if nc -z localhost 3001; then
              echo "Backend is up!"
              exit 0
            else
              echo "Waiting for backend..."
              sleep 2
            fi
          done
          echo "Backend did not start in time"
          exit 1

      - name: Run tests
        run: pnpm run test